version: '3.8'

networks:
  network-mariadb:
    driver: bridge
    name: network-mariadb

volumes:
  volume-mariadb:
    name: volume-mariadb

services:
  mariadb:
    container_name: mariadb
    image: mariadb:jammy
    networks:
      - network-mariadb
    #ports:
    #  - 3306:3306
    volumes:
      - volume-mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: toor
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5
    networks:
      - network-mariadb
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb